# Generated by Django 2.2.2 on 2019-07-02 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyd_dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='server',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scrapyd_dash.ScrapydServer'),
            preserve_default=False,
        ),
    ]
