# Generated by Django 2.2.2 on 2019-07-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyd_dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='stopping',
            field=models.BooleanField(default=False),
        ),
    ]
