# Generated by Django 2.2.2 on 2019-07-02 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyd_dash', '0002_task_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapydProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=256)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapyd_dash.ScrapydServer')),
            ],
            options={
                'db_table': 'scrapyd_dash_projects',
            },
        ),
        migrations.DeleteModel(
            name='ScrapydProjects',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=64),
        ),
    ]
