# Generated by Django 2.2.2 on 2019-07-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyd_dash', '0003_auto_20190702_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapydproject',
            old_name='project',
            new_name='name',
        ),
    ]
