# Generated by Django 2.2.2 on 2019-07-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyd_dash', '0005_auto_20190702_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='runtime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
