# Generated by Django 2.2.2 on 2019-07-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyd_dash', '0009_auto_20190702_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project_name',
            new_name='project',
        ),
        migrations.AlterField(
            model_name='task',
            name='finished_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
