# Generated by Django 2.2.2 on 2019-07-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyd_dash', '0010_auto_20190702_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project',
            new_name='project_name',
        ),
    ]
