# Generated by Django 2.2.2 on 2019-07-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyd_dash', '0011_auto_20190702_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='runtime',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
