# Generated by Django 2.2.2 on 2019-07-03 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyd_dash', '0012_auto_20190702_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project_name',
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scrapyd_dash.ScrapydProject'),
            preserve_default=False,
        ),
    ]
