# Generated by Django 2.2.2 on 2019-07-03 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyd_dash', '0013_auto_20190703_0615'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scrapydproject',
            unique_together={('server', 'name')},
        ),
    ]
