# Generated by Django 2.2.2 on 2019-07-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyd_dash', '0014_auto_20190703_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
