# Generated by Django 2.2.2 on 2019-07-06 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyd_dash', '0015_auto_20190704_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapydProjectVersion',
            fields=[
                ('version', models.CharField(max_length=125, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='scrapydproject',
            name='versions',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='scrapyd_dash.ScrapydProjectVersion'),
            preserve_default=False,
        ),
    ]
