# Generated by Django 2.2.2 on 2019-07-06 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyd_dash', '0016_auto_20190706_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapydproject',
            name='versions',
        ),
        migrations.AddField(
            model_name='scrapydprojectversion',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='scrapyd_dash.ScrapydProject'),
            preserve_default=False,
        ),
    ]
