# Generated by Django 2.2.2 on 2019-07-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyd_dash', '0017_auto_20190706_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
