# Generated by Django 2.2.2 on 2019-07-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyd_dash', '0018_auto_20190707_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtasks',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
