# Generated by Django 2.2.2 on 2019-06-26 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTasks',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('project', models.CharField(max_length=256)),
                ('spider', models.CharField(max_length=256)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(12)])),
                ('day', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(32)])),
                ('week', models.PositiveIntegerField()),
                ('day_of_week', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(7)])),
                ('hour', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(24)])),
                ('minute', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(60)])),
                ('second', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(60)])),
            ],
        ),
        migrations.CreateModel(
            name='ScrapydServer',
            fields=[
                ('ip', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('mode_name', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=64)),
                ('pending_tasks', models.PositiveIntegerField()),
                ('finished_tasks', models.PositiveIntegerField()),
                ('running_tasks', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('project', models.CharField(max_length=256)),
                ('spider', models.CharField(max_length=256)),
                ('status', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('pages', models.PositiveIntegerField(null=True)),
                ('items', models.PositiveIntegerField(null=True)),
                ('pid', models.PositiveIntegerField(null=True)),
                ('runtime', models.TimeField()),
                ('start_datetime', models.DateTimeField(auto_now_add=True)),
                ('finished_datetime', models.DateTimeField()),
                ('log_href', models.CharField(max_length=1024, null=True)),
                ('items_href', models.CharField(max_length=1024, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField()),
            ],
        ),
    ]
