# Generated by Django 2.2.2 on 2019-06-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapydserver',
            options={'ordering': ['-status']},
        ),
    ]
