# Generated by Django 2.2.2 on 2019-06-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapydserver',
            name='finished_tasks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scrapydserver',
            name='pending_tasks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scrapydserver',
            name='running_tasks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
